config/routes.rb
Rails.application.routes.draw do
  resources :contents
  devise_for :users
  root 'pages#home'

  get 'about' => 'pages#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ApplicationRecord
	
	extend FriendlyId
	friendly_id :titolo, use: :slugged

	belongs_to :user, optional: true

	has_many :sales

	has_attached_file :cover
  	validates_attachment_content_type :cover, content_type: /\Aimage\/.*\z/,
  	message:"Solo le immagini sono supportate"

  	has_attached_file :allegato
	validates_attachment_content_type :allegato, :content_type => [ /^image\/(png|gif|jpeg)/,'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/mspowerpoint','application/vnd.ms-powerpoint','application/vnd.openxmlformats-officedocument.presentationml.presentation', 'application/pdf', 'application/msexcel','application/vnd.ms-excel','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','audio/mpeg', 'audio/mp3' ],
	message:"Formato non supportato"

validates :titolo, :descrizione, :price, presence: true

validates :price, numericality: {greater_than: 49}

validates :cover, attachment_presence: true

validates :allegato, attachment_presence: true

end

app/models/sale.rb
class Sale < ApplicationRecord

before_create :generate_guid
belong_to :content

private 

	def generate_guid
		self.guid = SecureRandom.uuid()



end

app/models/user.rb
class User < ApplicationRecord
  

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :contents

   validates :name, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])

end

end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_content, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :check_user, only: [:edit, :update, :destroy]

  
  def index
    @contents = Content.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 7)
  end

  
  def show
  end

  
  def new
    @content = current_user.contents.build
  end

  def edit
  end

 
  def create
    @content = current_user.contents.build(content_params)

    respond_to do |format|
      if @content.save
        format.html { redirect_to @content, notice: 'Content was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

 
  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to @content, notice: 'Content was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

 
  def destroy
    @content.destroy
    respond_to do |format|
      format.html { redirect_to contents_url, notice: 'Content was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_content
      @content = Content.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def content_params
      params.require(:content).permit(:titolo, :descrizione, :price, :cover, :allegato)
    end

    def check_user

      if current_user != @content.user
        redirect_to root_url, alert: " Scusa ma non hai accesso a questa pagina"
      end    


    end  

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contents/_form.html.erb
<%= form_for @content, html: { multipart: true } do |f| %>
  <% if content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(content.errors.count, "error") %> prohibited this content from being saved:</h2>

      <ul>
      <% content.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <div class="field">
    <label>Carica il programma dettagliato del tuo tour</label>
    <br>
    <br>

    <%= f.file_field :allegato %>
  </div>

  <br>

  <div class="field">
    <%= f.label :titolo %>
    <%= f.text_field :titolo %>
  </div>

  <div class="field">
    <%= f.label :descrizione %>
    <%= f.text_area :descrizione, class: "materialize-textarea" %>
  </div>

  <div class="field">
    <%= f.label :Prezzo_min_50_cent %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :cover %>
    <%= f.file_field :cover %>
  </div>

  <br>

  <div class="actions">
    <%= f.submit 'Salva contenuto' , class:"btn btn-form" %>
  </div>

  <br>

<% end %>

app/views/contents/edit.html.erb
<h1 class="center">Modifica contenuto <%= @content.titolo %> </h1>

<%= render 'form', content: @content %>

<%= link_to 'Mostra contenuto', @content %> |
<%= link_to 'Torna ai contenuti', contents_path %> 

app/views/contents/index.html.erb
<p id="notice"><%= notice %></p>

<!--<h1>Contents</h1>-->

<div class="row">
  <% @contents.each do |content| %>
    <div class="col s4">
      <div class="card">
        <div class="card-image waves-effect waves-block waves-light">
          <%= image_tag content.cover.url, class: "activator" %>
        </div>
        <div class="card-content">
          <span class="card-title activator grey-text text-darken-4"><%= content.titolo %><i class="material-icons right">more_vert</i></span>          
            <div> 
              <span> Venduto da  <%= content.user.name %></span>
              <span class="right"> <%= number_to_currency(content.price) %></span>    
            </div>
            <br>
            <div class="center"><%= link_to 'Scopri di più', content, class:"btn" %></div>
            <% if content.user == current_user %>
            <br>
              <div class="center"><p><%= link_to 'Modifica contenuto', edit_content_path(content) %> <br>
              <%= link_to 'Elimina contenuto', content, method: :delete, data: { confirm: 'Sei sicuro di cancellare?' } %></p>
              </div>
            <% end %>  
          </div>
          <div class="card-reveal">
            <span class="card-title grey-text text-darken-4"><%= content.titolo %><i class="material-icons right">close</i></span>
            <p><%= content.descrizione %></p>
          </div>
      </div>
    </div>
  <% end %>  
</div>

<br>

<div class="center"> <%= will_paginate @contents %>
  
</div>

app/views/contents/new.html.erb
<h1 class="center">Vendi il tuo tour</h1>

<%= render 'form', content: @content %>

<%= link_to 'Torna ai contenuti', contents_path %>

app/views/contents/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
	<div class="col l6">
		<%= image_tag @content.cover.url, class:"responsive-img" %>
	</div>	

		<div class="col l6 ">
			<h1 class="show-titolo"> <%= @content.titolo %> </h1>

			<h4 class="show-price"><%= number_to_currency(@content.price) %></h4>

			<p> Venduto da <%= @content.user.name %></p>

			<p><%= @content.descrizione %></p>
			  
		</div>
</div>




	<% if @content.user == current_user %>
	<%= link_to 'Modifica contenuti', edit_content_path(@content) %> |
	<% end %>
<%= link_to 'Torna ai contenuti', contents_path %>

app/views/layouts/_footer.html.erb
<footer class="page-footer">
        
          <div class="footer-copyright">
            <div class="container">
              <div class="row">

               <div class="col s4">
                © 2014 Copyright Text

               </div>

               <div class="col s4">
               Social
               </div>

               <div class="col s4">
                <%= link_to "About", about_path, class: "grey-text text-lighten-4 right" %>
               </div>

              </div>






            </div>
          </div>
        </footer>

app/views/layouts/_header.html.erb
<header class="navbar-fixed">
      <nav>
        <div class="container nav-wrapper">
         <%=link_to "Toorist", root_path, class: "brand-logo" %>  
          <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
          <ul class="right hide-on-med-and-down">
                <li><%= link_to 'Vendi Tour', new_content_path %></li>
               <% if user_signed_in? %>
                 <li> <%=link_to "Log Out",  destroy_user_session_path, method: :delete %> </li>

                 <% else %>

                 <li> <%=link_to "Log in",  new_user_session_path %> </li> 

                 <li> <%=link_to "Registrazione",  new_user_registration_path %> </li> 

               <%end%> 

          </ul>
          <ul class="side-nav" id="mobile-demo">

                <li><%= link_to 'Vendi Tour', new_content_path %></li>

                <% if user_signed_in? %>
                 <li> <%=link_to "Log Out",  destroy_user_session_path, method: :delete %> </li>

                 <% else %>

                 <li> <%=link_to "Log in",  new_user_session_path %> </li> 

                 <li> <%=link_to "Registrazione",  new_user_registration_path %> </li> 

               <%end%> 

          </ul>
        </div>
      </nav>
  </header> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Toorist</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

  <body>

    <%= render "layouts/header" %>

       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

    <main class="container">

      <%= yield %>

    </main>
      <br>
      <%= render "layouts/footer" %>

    
  </body>

    <script> $(".button-collapse").sideNav(); </script>

</html>

app/views/pages/about.html.erb
<h1>Chi siamo</h1>

app/views/pages/home.html.erb
 
<h1> SAVERIO HOME TOORIST</h1>